// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDnGwo-aqUkDwowgVJGs77aryWlFFjTk',
    appId: '1:654184440551:web:6a2d07c05a203d79d07842',
    messagingSenderId: '654184440551',
    projectId: 'food-ca974',
    authDomain: 'food-ca974.firebaseapp.com',
    storageBucket: 'food-ca974.firebasestorage.app',
    measurementId: 'G-XN6D4RGQN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2xy6PsGrpO9HTsPLluPUXxGyfSx1IGM',
    appId: '1:654184440551:android:3180cd2246dcaed5d07842',
    messagingSenderId: '654184440551',
    projectId: 'food-ca974',
    storageBucket: 'food-ca974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQcNwVLrEVL9HYWjsijSnvxJz94yG4-s',
    appId: '1:654184440551:ios:03839a4b74e4848cd07842',
    messagingSenderId: '654184440551',
    projectId: 'food-ca974',
    storageBucket: 'food-ca974.firebasestorage.app',
    iosBundleId: 'com.example.food1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQcNwVLrEVL9HYWjsijSnvxJz94yG4-s',
    appId: '1:654184440551:ios:03839a4b74e4848cd07842',
    messagingSenderId: '654184440551',
    projectId: 'food-ca974',
    storageBucket: 'food-ca974.firebasestorage.app',
    iosBundleId: 'com.example.food1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxDnGwo-aqUkDwowgVJGs77aryWlFFjTk',
    appId: '1:654184440551:web:d3eed9536a3ae28dd07842',
    messagingSenderId: '654184440551',
    projectId: 'food-ca974',
    authDomain: 'food-ca974.firebaseapp.com',
    storageBucket: 'food-ca974.firebasestorage.app',
    measurementId: 'G-14TZ46B5EE',
  );
}
